### ISSUE TITLE
Frequently throwing this exception, after map scroll i guess 1.1.2

### ISSUE THREAD

**Issue by div-one** [FutureXpo/PUBG-RADAR-8K#3]
Exception in thread "main" java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.get(Unknown Source)
        at main.ui.GLMap.drawPlayerNames(GLMap.kt:1269)
        at main.ui.GLMap.render(GLMap.kt:596)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:386)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:136)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:110)
        at main.ui.GLMap.show(GLMap.kt:115)
        at main.GameKt.main(Game.kt:59)

**Comment by div-one** [comment]
midpc with arpspoof

**Comment by FutureXpo** [comment]
The problem in OpenGl. Try to reinstall it

**Comment by div-one** [comment]
Nope, still same exeption on this build

**Comment by FutureXpo** [comment]
Sry, i dont know how to fix this problem(only if you havent install something from [here](https://github.com/FutureXpo/PUBG-RADAR-8K#install))
